library/catalog/urls.py
from django.urls import path
from . import views
from .views import BookCreateView, BookDetailView, SignUpView, CheckedOutBooks

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_book/', BookCreateView.as_view(), name='book_create'),
    path('book_detail/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('my_view/', views.my_view, name='my_view'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', CheckedOutBooks.as_view(), name='profile')
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

library/catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Genre(models.Model):

    name = models.CharField(max_length=150)

    def __str__(self) -> str:
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=700)
    isbn = models.CharField('ISBN', max_length=40, unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return f'{self.title} Written by {self.author}'

    def get_absolute_url(self):
        return reverse("catalog:book_detail", kwargs={"pk": self.pk})


class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'last_name']

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.last_name}, {self.first_name}"


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    inprint = models.CharField(max_length=30)
    due_back = models.DateTimeField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'))

    status = models.CharField(
        max_length=1, choices=LOAN_STATUS, blank=True, default='m')

    class Meta:
        ordering = ['due_back']

    def __str__(self) -> str:
        return f'{self.id} {self.book.title}'

library/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, Author, BookInstance, Genre, Language
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
# Create your views here.


def index(request):

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_avail = BookInstance.objects.filter(
        status__exact='a').count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_avail': num_instances_avail
    }
    return render(request, 'catalog/index.html', context=context)


class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    fields = '__all__'


class BookDetailView(DetailView):
    model = Book


@login_required
def my_view(request):
    return render(request, 'catalog/my_view.html')


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'


class CheckedOutBooks(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'catalog/profile.html'

    paginate_by = 6

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).all()

library/catalog/templates/catalog/book_detail.html
<h1>BOOK DETAIL</h1>

{{book}}

library/catalog/templates/catalog/book_form.html
<h1>CREATE A NEW BOOK</h1>

<form method="POST">
  {% csrf_token %} {{form.as_p}}

  <input type="Submit" value="CREATE " />
</form>

library/catalog/templates/catalog/index.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Library Catalog</title>
  </head>
  <>
    <h1>HOME PAGE</h1>

    <p>Total Books: {{num_books}}</p>
    <p>Total Books: {{num_instances_avail}}</p>

    <h1>Welcome to Home.html</h1>

    <ul>
      <li>
        <a href="{% url 'catalog:book_create' %}"> CREATE A BOOK</a>
      </li>
    </ul>

    {% if user.is_authenticated %}
    <p>You are Logined</p>
    <p>Welcome  {{user.get_username}} </p>
    <a href="{% url 'logout' %}?next={{request.path}}">LOGOUT</a>

{% else %}
<p>Please Login</p>
<a href="{% url 'login' %}?next={{request.path}}">LOGIN</a>
      
    {% endif %}
  </body>
</html>

library/catalog/templates/catalog/my_view.html
<h1>LOGGED IN USERS ONLY</h1>

library/catalog/templates/catalog/profile.html
<h1>Welcome to your Profile</h1>
<h2>HJere are your books instance</h2>

{% for book in bookinstance_list %}

<p>{{book}}</p>

{% endfor %}

library/catalog/templates/catalog/signup.html
<h1>Register New User</h1>

<form method="POST">
  {%csrf_token%} {{form.as_p}}

  <input type="Submit" value="SIGNUP" />
</form>